# Generated by Django 2.0.6 on 2018-06-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_disponible', models.FloatField(verbose_name='Monto Disponible')),
                ('tasa', models.FloatField(max_length=80, verbose_name='Tasa de Interes')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('cedula', models.BigIntegerField(verbose_name='Cedula')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='capital',
            name='socio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.Socio'),
        ),
    ]
