# Generated by Django 2.0.6 on 2018-06-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capital',
            options={'ordering': ['-id'], 'verbose_name': 'Capital', 'verbose_name_plural': 'Capital'},
        ),
    ]
